apiVersion: v1
entries:
  kubevpn:
  - apiVersion: v2
    appVersion: v2.2.6
    created: "2024-04-16T05:44:31.777079658Z"
    description: A Helm chart for KubeVPN
    digest: 63668930b99e6c18f6dd77a25e5ce2d21579d52a83451f58be3bc0ca32678829
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.6/kubevpn-2.2.6.tgz
    version: 2.2.6
  - apiVersion: v2
    appVersion: v2.2.5
    created: "2024-04-14T08:46:13.877936123Z"
    description: A Helm chart for KubeVPN
    digest: 8509aeec7584935344bdf465efd8f0d5efb58ef1b7a31fd2738e5c2790f680c4
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.5/kubevpn-2.2.5.tgz
    version: 2.2.5
  - apiVersion: v2
    appVersion: v2.2.4
    created: "2024-04-02T05:15:00.372823536Z"
    description: A Helm chart for KubeVPN
    digest: 07e87e648b7ad5688146a356c93c1771e94485c2fd9d5441553d94ce6371c19f
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.4/kubevpn-2.2.4.tgz
    version: 2.2.4
  - apiVersion: v2
    appVersion: v2.2.3
    created: "2024-03-03T11:52:37.856463964Z"
    description: A Helm chart for KubeVPN
    digest: cb1b8c210259292488548853bdeb2eb9ef4c60d1643e0d6537174349514dc8e9
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.3/kubevpn-2.2.3.tgz
    version: 2.2.3
  - apiVersion: v2
    appVersion: v2.2.2
    created: "2024-02-15T13:35:35.121411893Z"
    description: A Helm chart for KubeVPN
    digest: b7589312eab83e50db9ae5703a30e76f0b40fd280c81d102a823aeeb61e14c1c
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.2/kubevpn-2.2.2.tgz
    version: 2.2.2
generated: "2024-04-16T05:44:31.777107661Z"
