apiVersion: v1
entries:
  kubevpn:
  - apiVersion: v2
    appVersion: v2.2.3
    created: "2024-03-03T11:52:37.856463964Z"
    description: A Helm chart for KubeVPN
    digest: cb1b8c210259292488548853bdeb2eb9ef4c60d1643e0d6537174349514dc8e9
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.3/kubevpn-2.2.3.tgz
    version: 2.2.3
  - apiVersion: v2
    appVersion: v2.2.2
    created: "2024-02-15T13:35:35.121411893Z"
    description: A Helm chart for KubeVPN
    digest: b7589312eab83e50db9ae5703a30e76f0b40fd280c81d102a823aeeb61e14c1c
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.2/kubevpn-2.2.2.tgz
    version: 2.2.2
generated: "2024-03-03T11:52:37.85647222Z"
