apiVersion: v1
entries:
  kubevpn:
  - apiVersion: v2
    appVersion: v2.2.13
    created: "2024-07-05T15:08:40.140645659Z"
    description: A Helm chart for KubeVPN
    digest: 610c5528952826839d5636b8bd940ac907ab0e70377e37538063cb53a5f75443
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.13/kubevpn-2.2.13.tgz
    version: 2.2.13
  - apiVersion: v2
    appVersion: v2.2.12
    created: "2024-06-29T15:36:12.429229459Z"
    description: A Helm chart for KubeVPN
    digest: a129ac0efda2e2967937407b904d59122e7b9725fb225c0bcbfdf2260337c032
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.12/kubevpn-2.2.12.tgz
    version: 2.2.12
  - apiVersion: v2
    appVersion: v2.2.11
    created: "2024-06-21T14:13:53.982206886Z"
    description: A Helm chart for KubeVPN
    digest: 3a7fa4cb3e1785da68e422ef151a3c7f621fbe76862b557ae2750af70d34e1ad
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.11/kubevpn-2.2.11.tgz
    version: 2.2.11
  - apiVersion: v2
    appVersion: v2.2.10
    created: "2024-05-21T06:46:20.368800554Z"
    description: A Helm chart for KubeVPN
    digest: 89be252c9eedb13560224550f06270f8be88049edfb0a46ca170ab5c8c493a6c
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.10/kubevpn-2.2.10.tgz
    version: 2.2.10
  - apiVersion: v2
    appVersion: v2.2.9
    created: "2024-05-14T11:50:54.700148975Z"
    description: A Helm chart for KubeVPN
    digest: e94debe7c904e21f791c1e3bb877ca8132888a3bb3c53beaa74e2ff1e7dd8769
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.9/kubevpn-2.2.9.tgz
    version: 2.2.9
  - apiVersion: v2
    appVersion: v2.2.8
    created: "2024-05-03T15:50:13.647253665Z"
    description: A Helm chart for KubeVPN
    digest: 9e18d0d02f123e5d8f096362daa5e6893d5db1e8447a632585ae23d6ce755489
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.8/kubevpn-2.2.8.tgz
    version: 2.2.8
  - apiVersion: v2
    appVersion: v2.2.7
    created: "2024-04-27T12:11:35.594701859Z"
    description: A Helm chart for KubeVPN
    digest: 3828f5b20d6bf4c0c7d94654cc33fd8d7b4c5f2aa20a3cc18d18b9298f459456
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.7/kubevpn-2.2.7.tgz
    version: 2.2.7
  - apiVersion: v2
    appVersion: v2.2.6
    created: "2024-04-16T05:44:31.777079658Z"
    description: A Helm chart for KubeVPN
    digest: 63668930b99e6c18f6dd77a25e5ce2d21579d52a83451f58be3bc0ca32678829
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.6/kubevpn-2.2.6.tgz
    version: 2.2.6
  - apiVersion: v2
    appVersion: v2.2.5
    created: "2024-04-14T08:46:13.877936123Z"
    description: A Helm chart for KubeVPN
    digest: 8509aeec7584935344bdf465efd8f0d5efb58ef1b7a31fd2738e5c2790f680c4
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.5/kubevpn-2.2.5.tgz
    version: 2.2.5
  - apiVersion: v2
    appVersion: v2.2.4
    created: "2024-04-02T05:15:00.372823536Z"
    description: A Helm chart for KubeVPN
    digest: 07e87e648b7ad5688146a356c93c1771e94485c2fd9d5441553d94ce6371c19f
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.4/kubevpn-2.2.4.tgz
    version: 2.2.4
  - apiVersion: v2
    appVersion: v2.2.3
    created: "2024-03-03T11:52:37.856463964Z"
    description: A Helm chart for KubeVPN
    digest: cb1b8c210259292488548853bdeb2eb9ef4c60d1643e0d6537174349514dc8e9
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.3/kubevpn-2.2.3.tgz
    version: 2.2.3
  - apiVersion: v2
    appVersion: v2.2.2
    created: "2024-02-15T13:35:35.121411893Z"
    description: A Helm chart for KubeVPN
    digest: b7589312eab83e50db9ae5703a30e76f0b40fd280c81d102a823aeeb61e14c1c
    name: kubevpn
    type: application
    urls:
    - https://github.com/kubenetworks/kubevpn/releases/download/v2.2.2/kubevpn-2.2.2.tgz
    version: 2.2.2
generated: "2024-07-05T15:08:40.140749013Z"
